/* tslint:disable */
/* eslint-disable */
/**
 * Bansay API
 * The Basay API, liability management system
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface CreateLiabilityDto
 */
export interface CreateLiabilityDto {
    /**
     * The student\'s username
     * @type {string}
     * @memberof CreateLiabilityDto
     */
    'studentUsername': string;
    /**
     * The type of liability
     * @type {string}
     * @memberof CreateLiabilityDto
     */
    'type': CreateLiabilityDtoTypeEnum;
    /**
     * The monetary amount of the liability
     * @type {number}
     * @memberof CreateLiabilityDto
     */
    'amount': number;
    /**
     * The date the liability is due (YYYY-MM-DD)
     * @type {string}
     * @memberof CreateLiabilityDto
     */
    'dueDate': string;
}

export const CreateLiabilityDtoTypeEnum = {
    Tuition: 'tuition',
    Fee: 'fee',
    Fine: 'fine',
    Other: 'other'
} as const;

export type CreateLiabilityDtoTypeEnum = typeof CreateLiabilityDtoTypeEnum[keyof typeof CreateLiabilityDtoTypeEnum];

/**
 * 
 * @export
 * @interface Liability
 */
export interface Liability {
    /**
     * 
     * @type {number}
     * @memberof Liability
     */
    'id': number;
    /**
     * 
     * @type {User}
     * @memberof Liability
     */
    'student': User;
    /**
     * 
     * @type {User}
     * @memberof Liability
     */
    'issuer': User;
    /**
     * 
     * @type {string}
     * @memberof Liability
     */
    'type': LiabilityTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof Liability
     */
    'amount': number;
    /**
     * 
     * @type {string}
     * @memberof Liability
     */
    'status': LiabilityStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Liability
     */
    'dueDate': string;
    /**
     * 
     * @type {string}
     * @memberof Liability
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof Liability
     */
    'updatedAt': string;
}

export const LiabilityTypeEnum = {
    Tuition: 'tuition',
    Fee: 'fee',
    Fine: 'fine',
    Other: 'other'
} as const;

export type LiabilityTypeEnum = typeof LiabilityTypeEnum[keyof typeof LiabilityTypeEnum];
export const LiabilityStatusEnum = {
    Unpaid: 'Unpaid',
    Paid: 'Paid',
    Cancelled: 'Cancelled'
} as const;

export type LiabilityStatusEnum = typeof LiabilityStatusEnum[keyof typeof LiabilityStatusEnum];

/**
 * 
 * @export
 * @interface LoginResponseDto
 */
export interface LoginResponseDto {
    /**
     * 
     * @type {string}
     * @memberof LoginResponseDto
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponseDto
     */
    'accessToken': string;
    /**
     * 
     * @type {UserInfoDto}
     * @memberof LoginResponseDto
     */
    'user': UserInfoDto;
}
/**
 * 
 * @export
 * @interface MyLiabilitiesResponseDto
 */
export interface MyLiabilitiesResponseDto {
    /**
     * 
     * @type {Array<Liability>}
     * @memberof MyLiabilitiesResponseDto
     */
    'liabilities': Array<Liability>;
    /**
     * The sum of all UNPAID liabilities
     * @type {number}
     * @memberof MyLiabilitiesResponseDto
     */
    'totalOutstandingBalance': number;
}
/**
 * 
 * @export
 * @interface OfficerDto
 */
export interface OfficerDto {
    /**
     * 
     * @type {number}
     * @memberof OfficerDto
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof OfficerDto
     */
    'fullName': string;
    /**
     * 
     * @type {string}
     * @memberof OfficerDto
     */
    'idNumber': string;
    /**
     * 
     * @type {string}
     * @memberof OfficerDto
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface RegisterResponseDto
 */
export interface RegisterResponseDto {
    /**
     * 
     * @type {string}
     * @memberof RegisterResponseDto
     */
    'message': string;
    /**
     * 
     * @type {RegistrationInfoDto}
     * @memberof RegisterResponseDto
     */
    'user': RegistrationInfoDto;
}
/**
 * 
 * @export
 * @interface RegistrationInfoDto
 */
export interface RegistrationInfoDto {
    /**
     * 
     * @type {number}
     * @memberof RegistrationInfoDto
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof RegistrationInfoDto
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationInfoDto
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationInfoDto
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationInfoDto
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationInfoDto
     */
    'role': string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationInfoDto
     */
    'status': string;
}
/**
 * 
 * @export
 * @interface StudentDto
 */
export interface StudentDto {
    /**
     * 
     * @type {number}
     * @memberof StudentDto
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof StudentDto
     */
    'fullName': string;
    /**
     * 
     * @type {string}
     * @memberof StudentDto
     */
    'idNumber': string;
    /**
     * 
     * @type {string}
     * @memberof StudentDto
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface StudentPatchDto
 */
export interface StudentPatchDto {
    /**
     * 
     * @type {string}
     * @memberof StudentPatchDto
     */
    'field': string;
    /**
     * 
     * @type {string}
     * @memberof StudentPatchDto
     */
    'value': string;
}
/**
 * 
 * @export
 * @interface StudentRegistrationDto
 */
export interface StudentRegistrationDto {
    /**
     * 
     * @type {string}
     * @memberof StudentRegistrationDto
     */
    'idNumber': string;
    /**
     * 
     * @type {string}
     * @memberof StudentRegistrationDto
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'role': UserRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'status': UserStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'updatedAt': string;
}

export const UserRoleEnum = {
    Admin: 'Admin',
    Officer: 'Officer',
    Student: 'Student'
} as const;

export type UserRoleEnum = typeof UserRoleEnum[keyof typeof UserRoleEnum];
export const UserStatusEnum = {
    Pending: 'Pending',
    Active: 'Active',
    Deactivated: 'Deactivated'
} as const;

export type UserStatusEnum = typeof UserStatusEnum[keyof typeof UserStatusEnum];

/**
 * 
 * @export
 * @interface UserInfoDto
 */
export interface UserInfoDto {
    /**
     * 
     * @type {number}
     * @memberof UserInfoDto
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof UserInfoDto
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof UserInfoDto
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserInfoDto
     */
    'role': string;
}
/**
 * 
 * @export
 * @interface UserLoginDto
 */
export interface UserLoginDto {
    /**
     * The username (Student or Staff ID)
     * @type {string}
     * @memberof UserLoginDto
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginDto
     */
    'password': string;
    /**
     * Role of the user
     * @type {string}
     * @memberof UserLoginDto
     */
    'role': string;
}
/**
 * 
 * @export
 * @interface UserRegisterDto
 */
export interface UserRegisterDto {
    /**
     * 
     * @type {string}
     * @memberof UserRegisterDto
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterDto
     */
    'lastName': string;
    /**
     * Student or Staff ID
     * @type {string}
     * @memberof UserRegisterDto
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterDto
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterDto
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterDto
     */
    'role': UserRegisterDtoRoleEnum;
}

export const UserRegisterDtoRoleEnum = {
    Admin: 'Admin',
    Officer: 'Officer',
    Student: 'Student'
} as const;

export type UserRegisterDtoRoleEnum = typeof UserRegisterDtoRoleEnum[keyof typeof UserRegisterDtoRoleEnum];


/**
 * AdminApi - axios parameter creator
 * @export
 */
export const AdminApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/admin`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminApi - functional programming interface
 * @export
 */
export const AdminApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminApi - factory interface
 * @export
 */
export const AdminApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.adminControllerFindAll(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminApi - object-oriented interface
 * @export
 * @class AdminApi
 * @extends {BaseAPI}
 */
export class AdminApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApi
     */
    public adminControllerFindAll(options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * AppApi - axios parameter creator
 * @export
 */
export const AppApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetHello: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AppApi - functional programming interface
 * @export
 */
export const AppApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AppApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async appControllerGetHello(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appControllerGetHello(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppApi.appControllerGetHello']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AppApi - factory interface
 * @export
 */
export const AppApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AppApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetHello(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.appControllerGetHello(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AppApi - object-oriented interface
 * @export
 * @class AppApi
 * @extends {BaseAPI}
 */
export class AppApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppApi
     */
    public appControllerGetHello(options?: RawAxiosRequestConfig) {
        return AppApiFp(this.configuration).appControllerGetHello(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerGetMe: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UserLoginDto} userLoginDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerLogin: async (userLoginDto: UserLoginDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userLoginDto' is not null or undefined
            assertParamExists('authControllerLogin', 'userLoginDto', userLoginDto)
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userLoginDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UserRegisterDto} userRegisterDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerRegister: async (userRegisterDto: UserRegisterDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userRegisterDto' is not null or undefined
            assertParamExists('authControllerRegister', 'userRegisterDto', userRegisterDto)
            const localVarPath = `/auth/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userRegisterDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerGetMe(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authControllerGetMe(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authControllerGetMe']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {UserLoginDto} userLoginDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerLogin(userLoginDto: UserLoginDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authControllerLogin(userLoginDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authControllerLogin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {UserRegisterDto} userRegisterDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerRegister(userRegisterDto: UserRegisterDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RegisterResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authControllerRegister(userRegisterDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authControllerRegister']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerGetMe(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.authControllerGetMe(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UserLoginDto} userLoginDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerLogin(userLoginDto: UserLoginDto, options?: RawAxiosRequestConfig): AxiosPromise<LoginResponseDto> {
            return localVarFp.authControllerLogin(userLoginDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UserRegisterDto} userRegisterDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerRegister(userRegisterDto: UserRegisterDto, options?: RawAxiosRequestConfig): AxiosPromise<RegisterResponseDto> {
            return localVarFp.authControllerRegister(userRegisterDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authControllerGetMe(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authControllerGetMe(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {UserLoginDto} userLoginDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authControllerLogin(userLoginDto: UserLoginDto, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authControllerLogin(userLoginDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {UserRegisterDto} userRegisterDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authControllerRegister(userRegisterDto: UserRegisterDto, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authControllerRegister(userRegisterDto, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * LiabilityApi - axios parameter creator
 * @export
 */
export const LiabilityApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new liability (Officer Only)
         * @param {CreateLiabilityDto} createLiabilityDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        liabilityControllerCreate: async (createLiabilityDto: CreateLiabilityDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createLiabilityDto' is not null or undefined
            assertParamExists('liabilityControllerCreate', 'createLiabilityDto', createLiabilityDto)
            const localVarPath = `/liability`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createLiabilityDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Find all liabilities (Officer/Admin Only)
         * @param {LiabilityControllerFindAllStatusEnum} [status] Filter by liability status
         * @param {string} [studentUsername] Filter by the student ID
         * @param {string} [sortBy] Field to sort by (e.g., \&#39;dueDate\&#39;, \&#39;amount\&#39;, \&#39;status\&#39;)
         * @param {LiabilityControllerFindAllSortOrderEnum} [sortOrder] Sorty order (\&#39;ASC\&#39; or \&#39;DESC\&#39;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        liabilityControllerFindAll: async (status?: LiabilityControllerFindAllStatusEnum, studentUsername?: string, sortBy?: string, sortOrder?: LiabilityControllerFindAllSortOrderEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/liability`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (studentUsername !== undefined) {
                localVarQueryParameter['studentUsername'] = studentUsername;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (sortOrder !== undefined) {
                localVarQueryParameter['sortOrder'] = sortOrder;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Find all liabilities for the logged-in student
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        liabilityControllerFindMy: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/liability/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Find one liability by ID (Officer/Admin Only)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        liabilityControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('liabilityControllerFindOne', 'id', id)
            const localVarPath = `/liability/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Soft-delete a liability (Officer/Admin Only)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        liabilityControllerSoftDelete: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('liabilityControllerSoftDelete', 'id', id)
            const localVarPath = `/liability/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a liability (Officer/Admin Only)
         * @param {string} id 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        liabilityControllerUpdate: async (id: string, body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('liabilityControllerUpdate', 'id', id)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('liabilityControllerUpdate', 'body', body)
            const localVarPath = `/liability/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LiabilityApi - functional programming interface
 * @export
 */
export const LiabilityApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LiabilityApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new liability (Officer Only)
         * @param {CreateLiabilityDto} createLiabilityDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async liabilityControllerCreate(createLiabilityDto: CreateLiabilityDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Liability>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.liabilityControllerCreate(createLiabilityDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LiabilityApi.liabilityControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Find all liabilities (Officer/Admin Only)
         * @param {LiabilityControllerFindAllStatusEnum} [status] Filter by liability status
         * @param {string} [studentUsername] Filter by the student ID
         * @param {string} [sortBy] Field to sort by (e.g., \&#39;dueDate\&#39;, \&#39;amount\&#39;, \&#39;status\&#39;)
         * @param {LiabilityControllerFindAllSortOrderEnum} [sortOrder] Sorty order (\&#39;ASC\&#39; or \&#39;DESC\&#39;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async liabilityControllerFindAll(status?: LiabilityControllerFindAllStatusEnum, studentUsername?: string, sortBy?: string, sortOrder?: LiabilityControllerFindAllSortOrderEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Liability>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.liabilityControllerFindAll(status, studentUsername, sortBy, sortOrder, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LiabilityApi.liabilityControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Find all liabilities for the logged-in student
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async liabilityControllerFindMy(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MyLiabilitiesResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.liabilityControllerFindMy(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LiabilityApi.liabilityControllerFindMy']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Find one liability by ID (Officer/Admin Only)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async liabilityControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Liability>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.liabilityControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LiabilityApi.liabilityControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Soft-delete a liability (Officer/Admin Only)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async liabilityControllerSoftDelete(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.liabilityControllerSoftDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LiabilityApi.liabilityControllerSoftDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a liability (Officer/Admin Only)
         * @param {string} id 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async liabilityControllerUpdate(id: string, body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Liability>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.liabilityControllerUpdate(id, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LiabilityApi.liabilityControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LiabilityApi - factory interface
 * @export
 */
export const LiabilityApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LiabilityApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new liability (Officer Only)
         * @param {CreateLiabilityDto} createLiabilityDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        liabilityControllerCreate(createLiabilityDto: CreateLiabilityDto, options?: RawAxiosRequestConfig): AxiosPromise<Liability> {
            return localVarFp.liabilityControllerCreate(createLiabilityDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Find all liabilities (Officer/Admin Only)
         * @param {LiabilityControllerFindAllStatusEnum} [status] Filter by liability status
         * @param {string} [studentUsername] Filter by the student ID
         * @param {string} [sortBy] Field to sort by (e.g., \&#39;dueDate\&#39;, \&#39;amount\&#39;, \&#39;status\&#39;)
         * @param {LiabilityControllerFindAllSortOrderEnum} [sortOrder] Sorty order (\&#39;ASC\&#39; or \&#39;DESC\&#39;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        liabilityControllerFindAll(status?: LiabilityControllerFindAllStatusEnum, studentUsername?: string, sortBy?: string, sortOrder?: LiabilityControllerFindAllSortOrderEnum, options?: RawAxiosRequestConfig): AxiosPromise<Array<Liability>> {
            return localVarFp.liabilityControllerFindAll(status, studentUsername, sortBy, sortOrder, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Find all liabilities for the logged-in student
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        liabilityControllerFindMy(options?: RawAxiosRequestConfig): AxiosPromise<MyLiabilitiesResponseDto> {
            return localVarFp.liabilityControllerFindMy(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Find one liability by ID (Officer/Admin Only)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        liabilityControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<Liability> {
            return localVarFp.liabilityControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Soft-delete a liability (Officer/Admin Only)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        liabilityControllerSoftDelete(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.liabilityControllerSoftDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a liability (Officer/Admin Only)
         * @param {string} id 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        liabilityControllerUpdate(id: string, body: object, options?: RawAxiosRequestConfig): AxiosPromise<Liability> {
            return localVarFp.liabilityControllerUpdate(id, body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LiabilityApi - object-oriented interface
 * @export
 * @class LiabilityApi
 * @extends {BaseAPI}
 */
export class LiabilityApi extends BaseAPI {
    /**
     * 
     * @summary Create a new liability (Officer Only)
     * @param {CreateLiabilityDto} createLiabilityDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LiabilityApi
     */
    public liabilityControllerCreate(createLiabilityDto: CreateLiabilityDto, options?: RawAxiosRequestConfig) {
        return LiabilityApiFp(this.configuration).liabilityControllerCreate(createLiabilityDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Find all liabilities (Officer/Admin Only)
     * @param {LiabilityControllerFindAllStatusEnum} [status] Filter by liability status
     * @param {string} [studentUsername] Filter by the student ID
     * @param {string} [sortBy] Field to sort by (e.g., \&#39;dueDate\&#39;, \&#39;amount\&#39;, \&#39;status\&#39;)
     * @param {LiabilityControllerFindAllSortOrderEnum} [sortOrder] Sorty order (\&#39;ASC\&#39; or \&#39;DESC\&#39;)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LiabilityApi
     */
    public liabilityControllerFindAll(status?: LiabilityControllerFindAllStatusEnum, studentUsername?: string, sortBy?: string, sortOrder?: LiabilityControllerFindAllSortOrderEnum, options?: RawAxiosRequestConfig) {
        return LiabilityApiFp(this.configuration).liabilityControllerFindAll(status, studentUsername, sortBy, sortOrder, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Find all liabilities for the logged-in student
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LiabilityApi
     */
    public liabilityControllerFindMy(options?: RawAxiosRequestConfig) {
        return LiabilityApiFp(this.configuration).liabilityControllerFindMy(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Find one liability by ID (Officer/Admin Only)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LiabilityApi
     */
    public liabilityControllerFindOne(id: string, options?: RawAxiosRequestConfig) {
        return LiabilityApiFp(this.configuration).liabilityControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Soft-delete a liability (Officer/Admin Only)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LiabilityApi
     */
    public liabilityControllerSoftDelete(id: string, options?: RawAxiosRequestConfig) {
        return LiabilityApiFp(this.configuration).liabilityControllerSoftDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a liability (Officer/Admin Only)
     * @param {string} id 
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LiabilityApi
     */
    public liabilityControllerUpdate(id: string, body: object, options?: RawAxiosRequestConfig) {
        return LiabilityApiFp(this.configuration).liabilityControllerUpdate(id, body, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const LiabilityControllerFindAllStatusEnum = {
    Unpaid: 'Unpaid',
    Paid: 'Paid',
    Cancelled: 'Cancelled'
} as const;
export type LiabilityControllerFindAllStatusEnum = typeof LiabilityControllerFindAllStatusEnum[keyof typeof LiabilityControllerFindAllStatusEnum];
/**
 * @export
 */
export const LiabilityControllerFindAllSortOrderEnum = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;
export type LiabilityControllerFindAllSortOrderEnum = typeof LiabilityControllerFindAllSortOrderEnum[keyof typeof LiabilityControllerFindAllSortOrderEnum];


/**
 * OfficerApi - axios parameter creator
 * @export
 */
export const OfficerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        officerControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/officer`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OfficerApi - functional programming interface
 * @export
 */
export const OfficerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OfficerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async officerControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<OfficerDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.officerControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OfficerApi.officerControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OfficerApi - factory interface
 * @export
 */
export const OfficerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OfficerApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        officerControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<OfficerDto>> {
            return localVarFp.officerControllerFindAll(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OfficerApi - object-oriented interface
 * @export
 * @class OfficerApi
 * @extends {BaseAPI}
 */
export class OfficerApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfficerApi
     */
    public officerControllerFindAll(options?: RawAxiosRequestConfig) {
        return OfficerApiFp(this.configuration).officerControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * StudentApi - axios parameter creator
 * @export
 */
export const StudentApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {StudentRegistrationDto} studentRegistrationDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        studentControllerCreate: async (studentRegistrationDto: StudentRegistrationDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'studentRegistrationDto' is not null or undefined
            assertParamExists('studentControllerCreate', 'studentRegistrationDto', studentRegistrationDto)
            const localVarPath = `/students`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(studentRegistrationDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        studentControllerDeleteStudent: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('studentControllerDeleteStudent', 'id', id)
            const localVarPath = `/students/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        studentControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/students`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {StudentPatchDto} studentPatchDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        studentControllerPatchStudent: async (id: string, studentPatchDto: StudentPatchDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('studentControllerPatchStudent', 'id', id)
            // verify required parameter 'studentPatchDto' is not null or undefined
            assertParamExists('studentControllerPatchStudent', 'studentPatchDto', studentPatchDto)
            const localVarPath = `/students/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(studentPatchDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StudentApi - functional programming interface
 * @export
 */
export const StudentApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = StudentApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {StudentRegistrationDto} studentRegistrationDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async studentControllerCreate(studentRegistrationDto: StudentRegistrationDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.studentControllerCreate(studentRegistrationDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StudentApi.studentControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async studentControllerDeleteStudent(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.studentControllerDeleteStudent(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StudentApi.studentControllerDeleteStudent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async studentControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<StudentDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.studentControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StudentApi.studentControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {StudentPatchDto} studentPatchDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async studentControllerPatchStudent(id: string, studentPatchDto: StudentPatchDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.studentControllerPatchStudent(id, studentPatchDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StudentApi.studentControllerPatchStudent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * StudentApi - factory interface
 * @export
 */
export const StudentApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = StudentApiFp(configuration)
    return {
        /**
         * 
         * @param {StudentRegistrationDto} studentRegistrationDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        studentControllerCreate(studentRegistrationDto: StudentRegistrationDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.studentControllerCreate(studentRegistrationDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        studentControllerDeleteStudent(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.studentControllerDeleteStudent(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        studentControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<StudentDto>> {
            return localVarFp.studentControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {StudentPatchDto} studentPatchDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        studentControllerPatchStudent(id: string, studentPatchDto: StudentPatchDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.studentControllerPatchStudent(id, studentPatchDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * StudentApi - object-oriented interface
 * @export
 * @class StudentApi
 * @extends {BaseAPI}
 */
export class StudentApi extends BaseAPI {
    /**
     * 
     * @param {StudentRegistrationDto} studentRegistrationDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StudentApi
     */
    public studentControllerCreate(studentRegistrationDto: StudentRegistrationDto, options?: RawAxiosRequestConfig) {
        return StudentApiFp(this.configuration).studentControllerCreate(studentRegistrationDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StudentApi
     */
    public studentControllerDeleteStudent(id: string, options?: RawAxiosRequestConfig) {
        return StudentApiFp(this.configuration).studentControllerDeleteStudent(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StudentApi
     */
    public studentControllerFindAll(options?: RawAxiosRequestConfig) {
        return StudentApiFp(this.configuration).studentControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {StudentPatchDto} studentPatchDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StudentApi
     */
    public studentControllerPatchStudent(id: string, studentPatchDto: StudentPatchDto, options?: RawAxiosRequestConfig) {
        return StudentApiFp(this.configuration).studentControllerPatchStudent(id, studentPatchDto, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {UserControllerGetUsersStatusEnum} [status] 
         * @param {UserControllerGetUsersRoleEnum} [role] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerGetUsers: async (status?: UserControllerGetUsersStatusEnum, role?: UserControllerGetUsersRoleEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (role !== undefined) {
                localVarQueryParameter['role'] = role;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerPatchUser: async (id: string, body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('userControllerPatchUser', 'id', id)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('userControllerPatchUser', 'body', body)
            const localVarPath = `/user/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {UserControllerGetUsersStatusEnum} [status] 
         * @param {UserControllerGetUsersRoleEnum} [role] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userControllerGetUsers(status?: UserControllerGetUsersStatusEnum, role?: UserControllerGetUsersRoleEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerGetUsers(status, role, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.userControllerGetUsers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userControllerPatchUser(id: string, body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerPatchUser(id, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.userControllerPatchUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @param {UserControllerGetUsersStatusEnum} [status] 
         * @param {UserControllerGetUsersRoleEnum} [role] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerGetUsers(status?: UserControllerGetUsersStatusEnum, role?: UserControllerGetUsersRoleEnum, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.userControllerGetUsers(status, role, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerPatchUser(id: string, body: object, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.userControllerPatchUser(id, body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
    /**
     * 
     * @param {UserControllerGetUsersStatusEnum} [status] 
     * @param {UserControllerGetUsersRoleEnum} [role] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public userControllerGetUsers(status?: UserControllerGetUsersStatusEnum, role?: UserControllerGetUsersRoleEnum, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).userControllerGetUsers(status, role, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public userControllerPatchUser(id: string, body: object, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).userControllerPatchUser(id, body, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const UserControllerGetUsersStatusEnum = {
    Pending: 'Pending',
    Active: 'Active',
    Deactivated: 'Deactivated'
} as const;
export type UserControllerGetUsersStatusEnum = typeof UserControllerGetUsersStatusEnum[keyof typeof UserControllerGetUsersStatusEnum];
/**
 * @export
 */
export const UserControllerGetUsersRoleEnum = {
    Admin: 'Admin',
    Officer: 'Officer',
    Student: 'Student'
} as const;
export type UserControllerGetUsersRoleEnum = typeof UserControllerGetUsersRoleEnum[keyof typeof UserControllerGetUsersRoleEnum];


